{{- $app := printf "%s" .Values.name }}
{{- $namespace := printf "%s" .Values.namespace }}

{{- $defaultPort := .Values.ingress.port }}

apiVersion: v1
kind: Service
metadata:
  namespace: {{ $namespace }}
  name: {{ $app }}
  labels:
    app: {{ $app }}
spec:
  ports:
{{- $highestPort := 0 }}
{{- range $index, $container := .Values.containers }}
{{- $containerName := printf "%s" $container.name }}

{{- $ingress := $container.ingress | default (dict) }}
{{- $port :=  $ingress.port | default $defaultPort }}

{{- if gt (int $port) (int $highestPort) }}
  {{- $highestPort = $port }}
{{- end }}

    - port: {{ $port }}
      targetPort: {{ $port }}
      name: {{ $containerName }}
{{ end }}


{{- $emptyPort := add $highestPort 1 }}

    - port: {{ $emptyPort }}
      targetPort: {{ $emptyPort }}
      name: empty
  selector:
    app: {{ $app }}
