{{- $app := printf "%s" .Values.name }}
{{- $namespace := printf "%s" .Values.namespace }}

{{- $port :=  .Values.ingress.port }}

apiVersion: v1
kind: Service
metadata:
  namespace: {{ $namespace }}
  name: {{ $app }}
  labels:
    app: {{ $app }}
spec:
  ports:
    - port: {{ $port }}
      targetPort: {{ $port }}
      name: {{ $app }}

{{- /* Define empty port */}}
{{- $emptyPort := add $port 1 }}

    - port: {{ $emptyPort }}
      targetPort: {{ $emptyPort }}
      name: empty
  selector:
    app: {{ $app }}