# name: change-me
# namespace: change-me
type: NodePort

image:
  registry: ghcr.io/silte
  # repository: change-me
  tag: latest
  # command: Override default defined by container

ingress:
  enabled: true
  # host: change-me
  # Path is string or list of strings
  # path: change-me
  blockedPaths: []
  port: 3000

# Node environment for the process.
nodeEnv: production

# Cloud environment for the process.
cloudEnv: production

# Log level for the logger.
logLevel: warn
noColor: true

replicaCount: 1

healthCheck:
  path: /healthz

# Read more about probes at https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes
k8sProbes:
  liveness:
    # Defaults to `$container.healthCheck.path`
    # path: /api/health/live
    timeoutSeconds: 4
    periodSeconds: 5
    successThreshold: 1
    failureThreshold: 5

  readiness:
    # Defaults to `$container.healthCheck.path`
    # path: /api/health/ready
    timeoutSeconds: 4
    periodSeconds: 5
    successThreshold: 1
    failureThreshold: 2

  startup:
    # Defaults to `$container.healthCheck.path`
    # path: /api/health/started
    initialDelaySeconds: 2
    timeoutSeconds: 4
    periodSeconds: 5
    successThreshold: 1
    failureThreshold: 10

resources:
  requests:
    {}
    # memory: 64Mi
    # cpu: 250m
  limits:
    {}
    # memory: 128Mi
    # cpu: 500m

# Custom app related variables
env: {}

# List of secrets names to be mapped to all containers
secrets: []
